spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRESQL_SERVICE_HOST}:${POSTGRESQL_SERVICE_PORT}/${POSTGRESQL_DATABASE}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  ssl:
    protocol: TLS
    enabled-protocols: TLSv1.3,TLSv1.2
    ciphers: >-
      TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
      TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      TLS_DHE_DSS_WITH_AES_128_GCM_SHA256
      TLS_DHE_DSS_WITH_AES_256_GCM_SHA384
      TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
      TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
      TLS_AES_128_GCM_SHA256
      TLS_AES_256_GCM_SHA384
      TLS_AES_128_CCM_SHA256
    key-store: ${SERVER_SSL_KEYSTORE}
    key-store-password: ${SERVER_SSL_KEYSTOREPASSWORD}
    trust-store: ${SERVER_SSL_TRUSTSTORE}
    trust-store-password: ${SERVER_SSL_TRUSTSTOREPASSWORD}
cwa:
  dcc:
    verification-server:
      enable-mtls: true
      base-url: ${CWA_DCC_VERIFICATIONSERVER_BASEURL}
      key-store-path: ${CWA_DCC_VERIFICATIONSERVER_KEYSTOREPATH}
      key-store-password: ${CWA_DCC_VERIFICATIONSERVER_KEYSTOREPASSWORD}
      trust-store-path: ${CWA_DCC_VERIFICATIONSERVER_TRUSTSTOREPATH}
      trust-store-password: ${CWA_DCC_VERIFICATIONSERVER_TRUSTSTOREPASSWORD}
      verify-hostnames: false
    signing-api-server:
      enable-mtls: true
      base-url: ${CWA_DCC_SIGNINGAPISERVER_BASEURL}
      key-store-path: ${CWA_DCC_SIGNINGAPISERVER_KEYSTOREPATH}
      key-store-password: ${CWA_DCC_SIGNINGAPISERVER_KEYSTOREPASSWORD}
      trust-store-password: ${CWA_DCC_SIGNINGAPISERVER_TRUSTSTOREPASSWORD}
      trust-store-path: ${CWA_DCC_SIGNINGAPISERVER_TRUSTSTOREPATH}
      api-key: ${CWA_DCC_SIGNINGAPISERVER_APIKEY:}
      verify-hostnames: true
      connection-close-workaround: ${CWA_DCC_SIGNINGAPISERVER_CONNECTIONCLOSEWORKAROUND:false}
    request:
      sizelimit: 10000
    cleanup:
      entity: ${CWA_DCC_CLEANUP_ENTITY:180}
      rate: ${CWA_DCC_CLEANUP_RATE:60000}
      registration-token: ${CWA_DCC_CLEANUP_REGISTRATIONTOKEN:21}
      dcc-data: ${CWA_DCC_CLEANUP_DCCDATA:4}
    lab-id-claim:
      claims-per-partner: ${CWA_DCC_LABIDCLAIM_CLAIMSPERPARTNER:10000}
      maximum-age: ${CWA_DCC_LABIDCLAIM_MAXIMUMAGE:30}
allowed-client-certificates: ${DCC_ALLOWEDCLIENTCERTIFICATES}
